### ISSUE TITLE
WebGL Support

### ISSUE THREAD

**Issue by rarafy** [rarafy/unimgpicker-plus#2]
I will implement it if there are enough requests.

**Comment by rarafy** [comment]
なんかちょっといじってたら出来ました。`Assets>Unimgpicker>Samples>Picker-plus.unity` シーンに実装しました。

![image](https://user-images.githubusercontent.com/33755507/173842901-f29c44ff-1b6f-4f96-8e64-03cf16539996.png)

**Comment by usirg** [comment]
@rarafy I am looking for a solution to load an image from the Gallery on an iPhone into a WebGL build. Do I understand correctly that your package supports this? On the README it says to look at the japanese README. I had it translated but there does not seem to be additional info regarding use on WebGL.

Any help would be greatly appreciated!
